/**
 * Phase 6 — reproducible benchmark.
 *
 * `npm run bench` runs two corpora through `compress()` at every level and
 * measures, with the real o200k tokenizer (never `chars/4`):
 *
 *   - average and aggregate token reduction,
 *   - the share of `critical` constraints that survive (the ledger's own
 *     verifier, not a model's opinion),
 *   - how many changes the ledger blocked.
 *
 * The two corpora are reported separately on purpose:
 *
 *   - `bench/corpus/phase0/` + `bench/corpus/phase2/` (40 prompts) are the
 *     existing regression fixtures — phase 0 hides filler *inside* protected
 *     regions to prove it survives untouched, phase 2 is system prompts
 *     written to measure the constraint extractor. Both are already terse by
 *     construction, so a near-zero reduction here is the expected, honest
 *     result, not a bug: it demonstrates the safety claim ("does not corrupt
 *     already-careful production prompts"), not the savings claim.
 *   - `bench/corpus/phase6/` (10 prompts) is new: everyday, unengineered
 *     requests in the voice people actually paste, padded with the framing
 *     and hedges Fast mode targets. This is where the savings claim is
 *     measured.
 *
 * Reporting only the first corpus would quietly repeat the dishonesty
 * docs/PLAN.md Section 0 row 5 flags in the old app ("70% avg token savings"
 * with no benchmark behind it) by picking the corpus that makes the number
 * look worst and calling it "the" number; reporting only the second would do
 * the same in the other direction. Both are published.
 *
 * The result is written to `bench/results/summary.json` (raw numbers, for
 * anything that wants to consume them programmatically) and
 * `bench/results/summary.md` (the tables), and the same content replaces the
 * marked block in `README.md` and `index.html` — so the numbers those files
 * show are never typed by hand, only regenerated by this script.
 *
 * AI mode is optional and off by default: it needs a real provider call, so
 * it only runs when the matching API key is in the environment
 * (`ANTHROPIC_API_KEY`, `OPENAI_API_KEY`, `GEMINI_API_KEY`). Without a key the
 * report says so explicitly rather than guessing — this is the debt
 * docs/PLAN.md §6.6 left for this phase ("ningún material público debe
 * afirmar un porcentaje para el modo IA" until it is measured for real).
 *
 * Local ML mode (docs/PLAN.md Phase 8) is optional too, for a different
 * reason: it needs no key, but the first run downloads a real ~57 MB ONNX
 * model over the network and then runs real on-device inference, which is
 * slow and would make every `npm run bench` (and every CI run that calls it)
 * network-dependent and much slower for a number this repo already has a
 * mechanism to report honestly as "not measured". It only runs when
 * `LOCAL_ML_BENCH=1` is set.
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compress } from '../src/core/compress';
import { findProtectedRanges } from '../src/core/segment';
import { LEVELS } from '../src/core/rules';
import type { Level } from '../src/core/rules';
import { CRITICAL_TYPES, extractConstraints, verifyConstraints } from '../src/core/ledger';
import { countOpenAiTokens } from '../src/core/tokenizers/openai';
import { PROVIDERS, runAiPipeline } from '../src/providers';
import type { ProviderClient } from '../src/providers';
import { runLocalMlCompression } from '../src/local-ml/pipeline';
import { loadLocalMlEngine } from '../src/local-ml/engine';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

interface CorpusGroup {
  id: string;
  title: string;
  blurb: string;
  titleEs: string;
  blurbEs: string;
  dirs: string[];
}

const CORPUS_GROUPS: CorpusGroup[] = [
  {
    id: 'production',
    title: 'Production-style system prompts',
    blurb:
      'bench/corpus/phase0 + bench/corpus/phase2 — regression fixtures written to be already careful. A near-zero reduction here is the expected result: nothing gets invented to cut.',
    titleEs: 'System prompts de estilo producción',
    blurbEs:
      'bench/corpus/phase0 + bench/corpus/phase2 — fixtures de regresión escritos para ser ya cuidadosos. Una reducción casi nula aquí es el resultado esperado: no se inventa nada que recortar.',
    dirs: ['bench/corpus/phase0', 'bench/corpus/phase2'],
  },
  {
    id: 'everyday',
    title: 'Everyday chat-style prompts',
    blurb:
      'bench/corpus/phase6 — unengineered requests padded with the framing and hedges people type without thinking about it.',
    titleEs: 'Prompts cotidianos de chat',
    blurbEs:
      'bench/corpus/phase6 — peticiones sin diseñar, con los marcos y muletillas que la gente escribe sin pensarlo.',
    dirs: ['bench/corpus/phase6'],
  },
];

const AI_SAMPLE_GROUP = 'everyday';
const AI_SAMPLE_SIZE = 5;
const AI_LEVEL: Level = 'balanced';

const LOCAL_ML_SAMPLE_GROUP = 'everyday';
/** On-device CPU inference is much slower than an API call; a small sample keeps `npm run bench` usable. */
const LOCAL_ML_SAMPLE_SIZE = 3;
const LOCAL_ML_LEVEL: Level = 'balanced';

const PROVIDER_ENV_VAR: Record<ProviderClient['id'], string> = {
  anthropic: 'ANTHROPIC_API_KEY',
  openai: 'OPENAI_API_KEY',
  gemini: 'GEMINI_API_KEY',
};

interface CorpusEntry {
  id: string;
  prompt: string;
}

interface LevelStats {
  level: Level;
  prompts: number;
  tokensBefore: number;
  tokensAfter: number;
  avgReductionPct: number;
  aggregateReductionPct: number;
  criticalTotal: number;
  criticalKept: number;
  criticalPreservedPct: number;
  blockedChanges: number;
  promptsWithBlockedChanges: number;
  protectedRegions: number;
  protectedRegionViolations: number;
}

interface AiProviderStats {
  provider: ProviderClient['id'];
  label: string;
  compressModel: string;
  verifyModel: string;
  prompts: number;
  criticalTotal: number;
  criticalKeptAfterRepair: number;
  criticalPreservedPct: number;
  totalCalls: number;
  totalRepairs: number;
  spentUsd: number;
}

interface AiSkipped {
  provider: ProviderClient['id'];
  label: string;
  reason: string;
}

interface LocalMlStats {
  prompts: number;
  criticalTotal: number;
  criticalKept: number;
  criticalPreservedPct: number;
  protectedRegions: number;
  protectedRegionViolations: number;
}

function loadCorpus(dirs: string[]): CorpusEntry[] {
  const entries: CorpusEntry[] = [];
  for (const dir of dirs) {
    const abs = join(ROOT, dir);
    // Only the numbered prompt files, e.g. "01-code-fence-js.md" — excludes
    // "README.md", which documents the corpus and is not itself a prompt.
    const files = readdirSync(abs)
      .filter((f) => /^\d+-.*\.md$/.test(f))
      .sort();
    for (const file of files) {
      entries.push({
        id: `${dir.split('/').pop()}/${file}`,
        prompt: readFileSync(join(abs, file), 'utf8'),
      });
    }
  }
  return entries;
}

async function benchFastMode(corpus: CorpusEntry[]): Promise<LevelStats[]> {
  const results: LevelStats[] = [];

  for (const level of LEVELS) {
    let tokensBefore = 0;
    let tokensAfter = 0;
    let pctSum = 0;
    let criticalTotal = 0;
    let criticalKept = 0;
    let blockedChanges = 0;
    let promptsWithBlockedChanges = 0;
    let protectedRegions = 0;
    let protectedRegionViolations = 0;

    for (const { prompt } of corpus) {
      const constraints = extractConstraints(prompt);
      // The bench enforces the ledger at every level, not just `aggressive`
      // (the product default per docs/PLAN.md §2): this is what makes
      // "critical constraints preserved" and "changes blocked" measurable at
      // Light and Balanced too, instead of only reporting the level where the
      // product already turns enforcement on.
      const { output, blocked, changes } = compress(prompt, level, {
        enforceLedger: true,
        constraints,
      });

      const [before, after] = await Promise.all([
        countOpenAiTokens(prompt),
        countOpenAiTokens(output),
      ]);
      tokensBefore += before;
      tokensAfter += after;
      pctSum += before > 0 ? (before - after) / before : 0;

      const critical = constraints.filter((c) => CRITICAL_TYPES.includes(c.type));
      criticalTotal += critical.length;
      const report = verifyConstraints(prompt, output, critical);
      criticalKept += critical.length - report.criticalLost.length;

      if (blocked.length > 0) {
        blockedChanges += blocked.length;
        promptsWithBlockedChanges += 1;
      }

      // docs/PLAN.md §5: "npm run bench ... shows 0 changes in protected
      // regions". Checked directly here, not only inferred from the separate
      // regression suite, so the acceptance criterion is verifiable from this
      // command's own output.
      const ranges = findProtectedRanges(prompt);
      protectedRegions += ranges.length;
      protectedRegionViolations += changes.filter((c) =>
        ranges.some((r) => c.start < r.end && r.start < c.end),
      ).length;
    }

    results.push({
      level,
      prompts: corpus.length,
      tokensBefore,
      tokensAfter,
      avgReductionPct: (pctSum / corpus.length) * 100,
      aggregateReductionPct:
        tokensBefore > 0 ? ((tokensBefore - tokensAfter) / tokensBefore) * 100 : 0,
      criticalTotal,
      criticalKept,
      criticalPreservedPct: criticalTotal > 0 ? (criticalKept / criticalTotal) * 100 : 100,
      blockedChanges,
      promptsWithBlockedChanges,
      protectedRegions,
      protectedRegionViolations,
    });
  }

  return results;
}

async function benchAiMode(
  corpus: CorpusEntry[],
): Promise<{ measured: AiProviderStats[]; skipped: AiSkipped[] }> {
  const measured: AiProviderStats[] = [];
  const skipped: AiSkipped[] = [];
  const sample = corpus.slice(0, AI_SAMPLE_SIZE);

  for (const provider of PROVIDERS) {
    const apiKey = process.env[PROVIDER_ENV_VAR[provider.id]];
    if (!apiKey) {
      skipped.push({
        provider: provider.id,
        label: provider.label,
        reason: `${PROVIDER_ENV_VAR[provider.id]} not set`,
      });
      continue;
    }

    let criticalTotal = 0;
    let criticalKeptAfterRepair = 0;
    let totalCalls = 0;
    let totalRepairs = 0;
    let inputTokens = 0;
    let outputTokens = 0;

    for (const { id, prompt } of sample) {
      try {
        const run = await runAiPipeline(prompt, {
          provider,
          apiKey,
          level: AI_LEVEL,
          compressModel: provider.defaultModel,
          verifyModel: provider.defaultVerifierModel,
        });
        const critical = run.constraints.filter((c) => CRITICAL_TYPES.includes(c.type));
        criticalTotal += critical.length;
        criticalKeptAfterRepair += run.report.checks.filter(
          (check) => CRITICAL_TYPES.includes(check.constraint.type) && check.preserved,
        ).length;
        totalCalls += run.calls;
        totalRepairs += run.repairs;
        inputTokens += run.usage.inputTokens;
        outputTokens += run.usage.outputTokens;
      } catch (err) {
        skipped.push({
          provider: provider.id,
          label: provider.label,
          reason: `failed on ${id}: ${(err as Error).message}`,
        });
      }
    }

    const model = provider.models.includes(provider.defaultModel) ? provider.defaultModel : null;
    const spentUsd = model
      ? await costForUsage(provider.defaultModel, inputTokens, outputTokens)
      : 0;

    measured.push({
      provider: provider.id,
      label: provider.label,
      compressModel: provider.defaultModel,
      verifyModel: provider.defaultVerifierModel,
      prompts: sample.length,
      criticalTotal,
      criticalKeptAfterRepair,
      criticalPreservedPct:
        criticalTotal > 0 ? (criticalKeptAfterRepair / criticalTotal) * 100 : 100,
      totalCalls,
      totalRepairs,
      spentUsd,
    });
  }

  return { measured, skipped };
}

/**
 * Measures Local ML mode for real: downloads the actual TinyBERT model (once,
 * cached by `@huggingface/transformers` under `~/.cache`) and runs real
 * on-device inference over a small sample, the same `runLocalMlCompression`
 * pipeline the UI calls. `{ device: 'cpu' }` is the Node-side config the
 * library's own README recommends; the browser instead auto-picks WebGPU or
 * WASM (see `src/local-ml/engine.ts`).
 */
async function benchLocalMl(corpus: CorpusEntry[]): Promise<LocalMlStats | null> {
  if (!process.env.LOCAL_ML_BENCH) return null;

  const sample = corpus.slice(0, LOCAL_ML_SAMPLE_SIZE);
  let criticalTotal = 0;
  let criticalKept = 0;
  let protectedRegions = 0;
  let protectedRegionViolations = 0;

  for (const { prompt } of sample) {
    const run = await runLocalMlCompression(prompt, {
      level: LOCAL_ML_LEVEL,
      loadEngine: (onProgress) => loadLocalMlEngine(onProgress, { device: 'cpu', dtype: 'fp32' }),
    });
    const critical = run.report.checks.filter((c) => CRITICAL_TYPES.includes(c.constraint.type));
    criticalTotal += critical.length;
    criticalKept += critical.filter((c) => c.preserved).length;

    const ranges = findProtectedRanges(prompt);
    protectedRegions += ranges.length;
    for (const range of ranges) {
      if (!run.output.includes(prompt.slice(range.start, range.end))) {
        protectedRegionViolations += 1;
      }
    }
  }

  return {
    prompts: sample.length,
    criticalTotal,
    criticalKept,
    criticalPreservedPct: criticalTotal > 0 ? (criticalKept / criticalTotal) * 100 : 100,
    protectedRegions,
    protectedRegionViolations,
  };
}

async function costForUsage(
  modelId: string,
  inputTokens: number,
  outputTokens: number,
): Promise<number> {
  const { getModel, costForTokens } = await import('../src/core/pricing');
  const model = getModel(modelId);
  if (!model) return 0;
  return (
    costForTokens(inputTokens, model.input_per_mtok) +
    costForTokens(outputTokens, model.output_per_mtok)
  );
}

function fmtPct(value: number): string {
  return `${value.toFixed(1)}%`;
}

function levelLabel(level: Level): string {
  return level[0]!.toUpperCase() + level.slice(1);
}

interface GroupResult {
  group: CorpusGroup;
  corpusSize: number;
  fast: LevelStats[];
}

function renderFastTable(result: GroupResult): string[] {
  const lines: string[] = [];
  lines.push(`**${result.group.title}** (${result.corpusSize} prompts)`);
  lines.push('');
  lines.push(`_${result.group.blurb}_`);
  lines.push('');
  lines.push(
    '| Level | Avg. token reduction | Aggregate token reduction | Critical constraints preserved | Changes blocked by the ledger |',
  );
  lines.push('|---|---|---|---|---|');
  for (const row of result.fast) {
    lines.push(
      `| ${levelLabel(row.level)} | ${fmtPct(row.avgReductionPct)} | ${fmtPct(row.aggregateReductionPct)} (${row.tokensBefore.toLocaleString()} → ${row.tokensAfter.toLocaleString()} tokens) | ${fmtPct(row.criticalPreservedPct)} (${row.criticalKept}/${row.criticalTotal}) | ${row.blockedChanges} (${row.promptsWithBlockedChanges} prompt${row.promptsWithBlockedChanges === 1 ? '' : 's'}) |`,
    );
  }
  lines.push('');
  return lines;
}

function renderMarkdown(
  today: string,
  groups: GroupResult[],
  ai: { measured: AiProviderStats[]; skipped: AiSkipped[] },
  localMl: LocalMlStats | null,
): string {
  const lines: string[] = [];
  lines.push(
    `_Generated by \`npm run bench\` on ${today}. Tokens counted with the real o200k tokenizer (\`js-tiktoken\`) — never estimated. The ledger is enforced at every level here (the product default only enforces it at Aggressive) so blocked changes are visible at all three._`,
  );
  lines.push('');

  for (const group of groups) {
    lines.push(...renderFastTable(group));
  }

  if (ai.measured.length > 0) {
    lines.push(
      `AI mode, Balanced level, ${AI_SAMPLE_SIZE}-prompt sample from the everyday corpus (a real provider call costs real money, so the sample is small on purpose):`,
    );
    lines.push('');
    lines.push(
      '| Provider | Compress model | Verify model | Critical constraints preserved | API calls | Repairs | Cost for the sample |',
    );
    lines.push('|---|---|---|---|---|---|---|');
    for (const row of ai.measured) {
      lines.push(
        `| ${row.label} | \`${row.compressModel}\` | \`${row.verifyModel}\` | ${fmtPct(row.criticalPreservedPct)} (${row.criticalKeptAfterRepair}/${row.criticalTotal}) | ${row.totalCalls} | ${row.totalRepairs} | $${row.spentUsd.toFixed(4)} |`,
      );
    }
    lines.push('');
  }
  if (ai.skipped.length > 0) {
    const names = [...new Set(ai.skipped.map((s) => s.label))].join(', ');
    lines.push(
      `AI mode not measured for: ${names}. Set the matching API key (\`ANTHROPIC_API_KEY\`, \`OPENAI_API_KEY\`, \`GEMINI_API_KEY\`) and re-run \`npm run bench\` to include it — no percentage is published for a provider that was not actually called.`,
    );
    lines.push('');
  }

  if (localMl) {
    lines.push(
      `Local ML mode (TinyBERT via LLMLingua-2, real on-device inference), Balanced level, ${localMl.prompts}-prompt sample from the everyday corpus:`,
    );
    lines.push('');
    lines.push('| Critical constraints preserved | Protected-region violations |');
    lines.push('|---|---|');
    lines.push(
      `| ${fmtPct(localMl.criticalPreservedPct)} (${localMl.criticalKept}/${localMl.criticalTotal}) | ${localMl.protectedRegionViolations}/${localMl.protectedRegions} |`,
    );
    lines.push('');
  } else {
    lines.push(
      'Local ML mode not measured: set `LOCAL_ML_BENCH=1` and re-run `npm run bench` to download the real ~57 MB TinyBERT model and measure it for real — no percentage is published for a mode that was not actually run.',
    );
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

type HtmlLang = 'en' | 'es';

const HTML_LABELS: Record<
  HtmlLang,
  {
    generatedBy: (today: string) => string;
    headers: [string, string, string, string, string];
    aiSample: string;
    aiHeaders: [string, string, string, string, string, string, string];
    aiSkipped: (names: string) => string;
    localMlSample: string;
    localMlHeaders: [string, string];
    localMlSkipped: string;
  }
> = {
  en: {
    generatedBy: (today) =>
      `<p class="advisor-sub">Generated by <code>npm run bench</code> on ${today}. Tokens counted with the real o200k tokenizer (js-tiktoken) — never estimated. The ledger is enforced at every level here (the product default only enforces it at Aggressive) so blocked changes are visible at all three.</p>`,
    headers: [
      'Level',
      'Avg. token reduction',
      'Aggregate token reduction',
      'Critical constraints preserved',
      'Changes blocked by the ledger',
    ],
    aiSample: `AI mode, Balanced level, ${AI_SAMPLE_SIZE}-prompt sample from the everyday corpus:`,
    aiHeaders: [
      'Provider',
      'Compress model',
      'Verify model',
      'Critical constraints preserved',
      'API calls',
      'Repairs',
      'Cost for the sample',
    ],
    aiSkipped: (names) =>
      `AI mode not measured for: ${names}. No percentage is published for a provider that was not actually called.`,
    localMlSample: `Local ML mode (TinyBERT via LLMLingua-2, real on-device inference), Balanced level, ${LOCAL_ML_SAMPLE_SIZE}-prompt sample from the everyday corpus:`,
    localMlHeaders: ['Critical constraints preserved', 'Protected-region violations'],
    localMlSkipped:
      'Local ML mode not measured: set LOCAL_ML_BENCH=1 and re-run npm run bench to download the real model and measure it. No percentage is published for a mode that was not actually run.',
  },
  es: {
    generatedBy: (today) =>
      `<p class="advisor-sub">Generado por <code>npm run bench</code> el ${today}. Tokens contados con el tokenizador real o200k (js-tiktoken) — nunca estimados. El libro de restricciones se aplica en todos los niveles aquí (el valor por defecto del producto solo lo aplica en Aggressive), así que los cambios bloqueados son visibles en los tres.</p>`,
    headers: [
      'Nivel',
      'Reducción media de tokens',
      'Reducción agregada de tokens',
      'Restricciones críticas preservadas',
      'Cambios bloqueados por el libro',
    ],
    aiSample: `Modo IA, nivel Balanced, muestra de ${AI_SAMPLE_SIZE} prompts del corpus cotidiano:`,
    aiHeaders: [
      'Proveedor',
      'Modelo de compresión',
      'Modelo de verificación',
      'Restricciones críticas preservadas',
      'Llamadas a la API',
      'Reparaciones',
      'Costo de la muestra',
    ],
    aiSkipped: (names) =>
      `Modo IA no medido para: ${names}. No se publica ningún porcentaje para un proveedor que no fue realmente llamado.`,
    localMlSample: `Modo ML local (TinyBERT vía LLMLingua-2, inferencia real en el dispositivo), nivel Balanced, muestra de ${LOCAL_ML_SAMPLE_SIZE} prompts del corpus cotidiano:`,
    localMlHeaders: ['Restricciones críticas preservadas', 'Violaciones de regiones protegidas'],
    localMlSkipped:
      'Modo ML local no medido: define LOCAL_ML_BENCH=1 y vuelve a ejecutar npm run bench para descargar el modelo real y medirlo. No se publica ningún porcentaje para un modo que no se ejecutó realmente.',
  },
};

/**
 * The landing page is static HTML, not a markdown renderer: the same numbers
 * as `renderMarkdown` above, as a real `<table>` reusing the Cost Advisor's
 * existing `.advisor-scroll`/`.advisor-table` styles rather than inventing a
 * parallel set of CSS just for this section. Rendered once per shipped
 * language (docs/PLAN.md Phase 6 task 5) so the Spanish landing never shows
 * numbers typed by hand either.
 */
function renderHtml(
  today: string,
  groups: GroupResult[],
  ai: { measured: AiProviderStats[]; skipped: AiSkipped[] },
  localMl: LocalMlStats | null,
  lang: HtmlLang,
): string {
  const t = HTML_LABELS[lang];
  const lines: string[] = [];
  lines.push(t.generatedBy(today));

  for (const result of groups) {
    const title = lang === 'es' ? result.group.titleEs : result.group.title;
    const blurb = lang === 'es' ? result.group.blurbEs : result.group.blurb;
    lines.push(`<h3>${escapeHtml(title)} (${result.corpusSize} prompts)</h3>`);
    lines.push(`<p class="advisor-sub">${escapeHtml(blurb)}</p>`);
    lines.push('<div class="advisor-scroll"><table class="advisor-table">');
    lines.push(
      `<thead><tr><th scope="col">${t.headers[0]}</th><th scope="col">${t.headers[1]}</th><th scope="col">${t.headers[2]}</th><th scope="col">${t.headers[3]}</th><th scope="col">${t.headers[4]}</th></tr></thead>`,
    );
    lines.push('<tbody>');
    for (const row of result.fast) {
      lines.push(
        `<tr><th scope="row">${levelLabel(row.level)}</th><td>${fmtPct(row.avgReductionPct)}</td><td>${fmtPct(row.aggregateReductionPct)} (${row.tokensBefore.toLocaleString()} → ${row.tokensAfter.toLocaleString()})</td><td>${fmtPct(row.criticalPreservedPct)} (${row.criticalKept}/${row.criticalTotal})</td><td>${row.blockedChanges}</td></tr>`,
      );
    }
    lines.push('</tbody></table></div>');
  }

  if (ai.measured.length > 0) {
    lines.push(`<p class="advisor-sub">${t.aiSample}</p>`);
    lines.push('<div class="advisor-scroll"><table class="advisor-table">');
    lines.push(
      `<thead><tr><th scope="col">${t.aiHeaders[0]}</th><th scope="col">${t.aiHeaders[1]}</th><th scope="col">${t.aiHeaders[2]}</th><th scope="col">${t.aiHeaders[3]}</th><th scope="col">${t.aiHeaders[4]}</th><th scope="col">${t.aiHeaders[5]}</th><th scope="col">${t.aiHeaders[6]}</th></tr></thead>`,
    );
    lines.push('<tbody>');
    for (const row of ai.measured) {
      lines.push(
        `<tr><th scope="row">${escapeHtml(row.label)}</th><td>${escapeHtml(row.compressModel)}</td><td>${escapeHtml(row.verifyModel)}</td><td>${fmtPct(row.criticalPreservedPct)} (${row.criticalKeptAfterRepair}/${row.criticalTotal})</td><td>${row.totalCalls}</td><td>${row.totalRepairs}</td><td>$${row.spentUsd.toFixed(4)}</td></tr>`,
      );
    }
    lines.push('</tbody></table></div>');
  }
  if (ai.skipped.length > 0) {
    const names = [...new Set(ai.skipped.map((s) => s.label))].join(', ');
    lines.push(`<p class="advisor-sub">${t.aiSkipped(escapeHtml(names))}</p>`);
  }

  if (localMl) {
    lines.push(`<p class="advisor-sub">${t.localMlSample}</p>`);
    lines.push('<div class="advisor-scroll"><table class="advisor-table">');
    lines.push(
      `<thead><tr><th scope="col">${t.localMlHeaders[0]}</th><th scope="col">${t.localMlHeaders[1]}</th></tr></thead>`,
    );
    lines.push(
      `<tbody><tr><td>${fmtPct(localMl.criticalPreservedPct)} (${localMl.criticalKept}/${localMl.criticalTotal})</td><td>${localMl.protectedRegionViolations}/${localMl.protectedRegions}</td></tr></tbody>`,
    );
    lines.push('</table></div>');
  } else {
    lines.push(`<p class="advisor-sub">${t.localMlSkipped}</p>`);
  }

  return lines.join('\n');
}

function updateMarkedBlock(filePath: string, marker: string, content: string): void {
  const start = `<!-- BENCHMARK:${marker}:START -->`;
  const end = `<!-- BENCHMARK:${marker}:END -->`;
  const text = readFileSync(filePath, 'utf8');
  const startIdx = text.indexOf(start);
  const endIdx = text.indexOf(end);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`bench: markers "${marker}" not found in ${filePath}`);
  }
  const before = text.slice(0, startIdx + start.length);
  const after = text.slice(endIdx);
  writeFileSync(filePath, `${before}\n${content}\n${after}`);
}

async function main(): Promise<void> {
  const today = new Date().toISOString().slice(0, 10);

  const groupResults: GroupResult[] = [];
  let aiCorpus: CorpusEntry[] = [];
  let localMlCorpus: CorpusEntry[] = [];
  for (const group of CORPUS_GROUPS) {
    const corpus = loadCorpus(group.dirs);
    console.log(`Running bench on "${group.title}" (${corpus.length} prompts)…`);
    const fast = await benchFastMode(corpus);
    groupResults.push({ group, corpusSize: corpus.length, fast });
    if (group.id === AI_SAMPLE_GROUP) aiCorpus = corpus;
    if (group.id === LOCAL_ML_SAMPLE_GROUP) localMlCorpus = corpus;
  }

  const ai = await benchAiMode(aiCorpus);
  if (process.env.LOCAL_ML_BENCH) {
    console.log('LOCAL_ML_BENCH=1: downloading the real TinyBERT model and measuring it…');
  }
  const localMl = await benchLocalMl(localMlCorpus);
  const markdown = renderMarkdown(today, groupResults, ai, localMl);
  const html = renderHtml(today, groupResults, ai, localMl, 'en');
  const htmlEs = renderHtml(today, groupResults, ai, localMl, 'es');

  const resultsDir = join(ROOT, 'bench', 'results');
  mkdirSync(resultsDir, { recursive: true });
  writeFileSync(
    join(resultsDir, 'summary.json'),
    JSON.stringify(
      {
        generatedAt: today,
        groups: groupResults.map((g) => ({
          id: g.group.id,
          title: g.group.title,
          corpusSize: g.corpusSize,
          fast: g.fast,
        })),
        ai,
        localMl,
      },
      null,
      2,
    ) + '\n',
  );
  writeFileSync(join(resultsDir, 'summary.md'), markdown + '\n');

  updateMarkedBlock(join(ROOT, 'README.md'), 'README', markdown);
  updateMarkedBlock(join(ROOT, 'index.html'), 'LANDING', html);
  updateMarkedBlock(join(ROOT, 'es', 'index.html'), 'LANDING', htmlEs);

  let totalProtectedRegions = 0;
  let totalProtectedRegionViolations = 0;
  let totalCritical = 0;
  let totalCriticalKept = 0;
  for (const { group, fast } of groupResults) {
    for (const row of fast) {
      console.log(
        `[${group.id}] ${levelLabel(row.level)}: ${fmtPct(row.avgReductionPct)} avg reduction, ${fmtPct(row.criticalPreservedPct)} critical constraints preserved, ${row.blockedChanges} blocked changes, ${row.protectedRegionViolations}/${row.protectedRegions} protected-region violations`,
      );
      totalProtectedRegions += row.protectedRegions;
      totalProtectedRegionViolations += row.protectedRegionViolations;
      totalCritical += row.criticalTotal;
      totalCriticalKept += row.criticalKept;
    }
  }

  const overallCriticalPct = totalCritical > 0 ? (totalCriticalKept / totalCritical) * 100 : 100;
  console.log(
    `\nProtected regions: ${totalProtectedRegionViolations} changes touched a protected region, out of ${totalProtectedRegions} protected-region checks across both corpora and all three levels.`,
  );
  console.log(
    `Critical constraints preserved overall: ${fmtPct(overallCriticalPct)} (${totalCriticalKept}/${totalCritical}).`,
  );
  // docs/PLAN.md §5 acceptance: 0 protected-region changes, >= 98% of
  // critical constraints preserved.
  if (totalProtectedRegionViolations > 0) {
    console.error('FAIL: a rule touched a protected region. See docs/PLAN.md §5.');
    process.exitCode = 1;
  }
  if (overallCriticalPct < 98) {
    console.error(
      `FAIL: only ${fmtPct(overallCriticalPct)} of critical constraints preserved (need >= 98%). See docs/PLAN.md §5.`,
    );
    process.exitCode = 1;
  }
  if (ai.measured.length) {
    for (const row of ai.measured) {
      console.log(
        `AI ${row.label}: ${fmtPct(row.criticalPreservedPct)} critical constraints preserved`,
      );
    }
  }
  if (ai.skipped.length) {
    console.log(`AI mode skipped for: ${[...new Set(ai.skipped.map((s) => s.label))].join(', ')}`);
  }
  if (localMl) {
    console.log(
      `Local ML: ${fmtPct(localMl.criticalPreservedPct)} critical constraints preserved, ${localMl.protectedRegionViolations}/${localMl.protectedRegions} protected-region violations`,
    );
    // Unlike AI mode's critical-preserved rate (a real model's judgment, no
    // hard floor expected), 0 protected-region violations is a structural
    // guarantee of `compressProtectedAware` (docs/PLAN.md Phase 8 task 2),
    // not a quality metric — a violation here means the wrapper has a bug.
    if (localMl.protectedRegionViolations > 0) {
      console.error('FAIL: Local ML mode touched a protected region. See docs/PLAN.md Phase 8.');
      process.exitCode = 1;
    }
  } else {
    console.log('Local ML mode skipped (set LOCAL_ML_BENCH=1 to measure it for real).');
  }

  console.log(
    '\nWritten: bench/results/summary.json, bench/results/summary.md, README.md, index.html, es/index.html',
  );
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
