/**
 * Phase 6 — reproducible benchmark.
 *
 * `npm run bench` runs two corpora through `compress()` at every level and
 * measures, with the real o200k tokenizer (never `chars/4`):
 *
 *   - average and aggregate token reduction,
 *   - the share of `critical` constraints that survive (the ledger's own
 *     verifier, not a model's opinion),
 *   - how many changes the ledger blocked.
 *
 * The two corpora are reported separately on purpose:
 *
 *   - `bench/corpus/phase0/` + `bench/corpus/phase2/` (40 prompts) are the
 *     existing regression fixtures — phase 0 hides filler *inside* protected
 *     regions to prove it survives untouched, phase 2 is system prompts
 *     written to measure the constraint extractor. Both are already terse by
 *     construction, so a near-zero reduction here is the expected, honest
 *     result, not a bug: it demonstrates the safety claim ("does not corrupt
 *     already-careful production prompts"), not the savings claim.
 *   - `bench/corpus/phase6/` (10 prompts) is new: everyday, unengineered
 *     requests in the voice people actually paste, padded with the framing
 *     and hedges Fast mode targets. This is where the savings claim is
 *     measured.
 *
 * Reporting only the first corpus would quietly repeat the dishonesty
 * docs/PLAN.md Section 0 row 5 flags in the old app ("70% avg token savings"
 * with no benchmark behind it) by picking the corpus that makes the number
 * look worst and calling it "the" number; reporting only the second would do
 * the same in the other direction. Both are published.
 *
 * The result is written to `bench/results/summary.json` (raw numbers, for
 * anything that wants to consume them programmatically) and
 * `bench/results/summary.md` (the tables), and the same content replaces the
 * marked block in `README.md` and `index.html` — so the numbers those files
 * show are never typed by hand, only regenerated by this script.
 *
 * AI mode is optional and off by default: it needs a real provider call, so
 * it only runs when the matching API key is in the environment
 * (`ANTHROPIC_API_KEY`, `OPENAI_API_KEY`, `GEMINI_API_KEY`). Without a key the
 * report says so explicitly rather than guessing — this is the debt
 * docs/PLAN.md §6.6 left for this phase ("ningún material público debe
 * afirmar un porcentaje para el modo IA" until it is measured for real).
 */

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compress } from '../src/core/compress';
import { LEVELS } from '../src/core/rules';
import type { Level } from '../src/core/rules';
import { CRITICAL_TYPES, extractConstraints, verifyConstraints } from '../src/core/ledger';
import { countOpenAiTokens } from '../src/core/tokenizers/openai';
import { PROVIDERS, runAiPipeline } from '../src/providers';
import type { ProviderClient } from '../src/providers';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

interface CorpusGroup {
  id: string;
  title: string;
  blurb: string;
  dirs: string[];
}

const CORPUS_GROUPS: CorpusGroup[] = [
  {
    id: 'production',
    title: 'Production-style system prompts',
    blurb:
      'bench/corpus/phase0 + bench/corpus/phase2 — regression fixtures written to be already careful. A near-zero reduction here is the expected result: nothing gets invented to cut.',
    dirs: ['bench/corpus/phase0', 'bench/corpus/phase2'],
  },
  {
    id: 'everyday',
    title: 'Everyday chat-style prompts',
    blurb:
      'bench/corpus/phase6 — unengineered requests padded with the framing and hedges people type without thinking about it.',
    dirs: ['bench/corpus/phase6'],
  },
];

const AI_SAMPLE_GROUP = 'everyday';
const AI_SAMPLE_SIZE = 5;
const AI_LEVEL: Level = 'balanced';

const PROVIDER_ENV_VAR: Record<ProviderClient['id'], string> = {
  anthropic: 'ANTHROPIC_API_KEY',
  openai: 'OPENAI_API_KEY',
  gemini: 'GEMINI_API_KEY',
};

interface CorpusEntry {
  id: string;
  prompt: string;
}

interface LevelStats {
  level: Level;
  prompts: number;
  tokensBefore: number;
  tokensAfter: number;
  avgReductionPct: number;
  aggregateReductionPct: number;
  criticalTotal: number;
  criticalKept: number;
  criticalPreservedPct: number;
  blockedChanges: number;
  promptsWithBlockedChanges: number;
}

interface AiProviderStats {
  provider: ProviderClient['id'];
  label: string;
  compressModel: string;
  verifyModel: string;
  prompts: number;
  criticalTotal: number;
  criticalKeptAfterRepair: number;
  criticalPreservedPct: number;
  totalCalls: number;
  totalRepairs: number;
  spentUsd: number;
}

interface AiSkipped {
  provider: ProviderClient['id'];
  label: string;
  reason: string;
}

function loadCorpus(dirs: string[]): CorpusEntry[] {
  const entries: CorpusEntry[] = [];
  for (const dir of dirs) {
    const abs = join(ROOT, dir);
    // Only the numbered prompt files, e.g. "01-code-fence-js.md" — excludes
    // "README.md", which documents the corpus and is not itself a prompt.
    const files = readdirSync(abs)
      .filter((f) => /^\d+-.*\.md$/.test(f))
      .sort();
    for (const file of files) {
      entries.push({
        id: `${dir.split('/').pop()}/${file}`,
        prompt: readFileSync(join(abs, file), 'utf8'),
      });
    }
  }
  return entries;
}

async function benchFastMode(corpus: CorpusEntry[]): Promise<LevelStats[]> {
  const results: LevelStats[] = [];

  for (const level of LEVELS) {
    let tokensBefore = 0;
    let tokensAfter = 0;
    let pctSum = 0;
    let criticalTotal = 0;
    let criticalKept = 0;
    let blockedChanges = 0;
    let promptsWithBlockedChanges = 0;

    for (const { prompt } of corpus) {
      const constraints = extractConstraints(prompt);
      // The bench enforces the ledger at every level, not just `aggressive`
      // (the product default per docs/PLAN.md §2): this is what makes
      // "critical constraints preserved" and "changes blocked" measurable at
      // Light and Balanced too, instead of only reporting the level where the
      // product already turns enforcement on.
      const { output, blocked } = compress(prompt, level, {
        enforceLedger: true,
        constraints,
      });

      const [before, after] = await Promise.all([
        countOpenAiTokens(prompt),
        countOpenAiTokens(output),
      ]);
      tokensBefore += before;
      tokensAfter += after;
      pctSum += before > 0 ? (before - after) / before : 0;

      const critical = constraints.filter((c) => CRITICAL_TYPES.includes(c.type));
      criticalTotal += critical.length;
      const report = verifyConstraints(prompt, output, critical);
      criticalKept += critical.length - report.criticalLost.length;

      if (blocked.length > 0) {
        blockedChanges += blocked.length;
        promptsWithBlockedChanges += 1;
      }
    }

    results.push({
      level,
      prompts: corpus.length,
      tokensBefore,
      tokensAfter,
      avgReductionPct: (pctSum / corpus.length) * 100,
      aggregateReductionPct:
        tokensBefore > 0 ? ((tokensBefore - tokensAfter) / tokensBefore) * 100 : 0,
      criticalTotal,
      criticalKept,
      criticalPreservedPct: criticalTotal > 0 ? (criticalKept / criticalTotal) * 100 : 100,
      blockedChanges,
      promptsWithBlockedChanges,
    });
  }

  return results;
}

async function benchAiMode(
  corpus: CorpusEntry[],
): Promise<{ measured: AiProviderStats[]; skipped: AiSkipped[] }> {
  const measured: AiProviderStats[] = [];
  const skipped: AiSkipped[] = [];
  const sample = corpus.slice(0, AI_SAMPLE_SIZE);

  for (const provider of PROVIDERS) {
    const apiKey = process.env[PROVIDER_ENV_VAR[provider.id]];
    if (!apiKey) {
      skipped.push({
        provider: provider.id,
        label: provider.label,
        reason: `${PROVIDER_ENV_VAR[provider.id]} not set`,
      });
      continue;
    }

    let criticalTotal = 0;
    let criticalKeptAfterRepair = 0;
    let totalCalls = 0;
    let totalRepairs = 0;
    let inputTokens = 0;
    let outputTokens = 0;

    for (const { id, prompt } of sample) {
      try {
        const run = await runAiPipeline(prompt, {
          provider,
          apiKey,
          level: AI_LEVEL,
          compressModel: provider.defaultModel,
          verifyModel: provider.defaultVerifierModel,
        });
        const critical = run.constraints.filter((c) => CRITICAL_TYPES.includes(c.type));
        criticalTotal += critical.length;
        criticalKeptAfterRepair += run.report.checks.filter(
          (check) => CRITICAL_TYPES.includes(check.constraint.type) && check.preserved,
        ).length;
        totalCalls += run.calls;
        totalRepairs += run.repairs;
        inputTokens += run.usage.inputTokens;
        outputTokens += run.usage.outputTokens;
      } catch (err) {
        skipped.push({
          provider: provider.id,
          label: provider.label,
          reason: `failed on ${id}: ${(err as Error).message}`,
        });
      }
    }

    const model = provider.models.includes(provider.defaultModel) ? provider.defaultModel : null;
    const spentUsd = model
      ? await costForUsage(provider.defaultModel, inputTokens, outputTokens)
      : 0;

    measured.push({
      provider: provider.id,
      label: provider.label,
      compressModel: provider.defaultModel,
      verifyModel: provider.defaultVerifierModel,
      prompts: sample.length,
      criticalTotal,
      criticalKeptAfterRepair,
      criticalPreservedPct:
        criticalTotal > 0 ? (criticalKeptAfterRepair / criticalTotal) * 100 : 100,
      totalCalls,
      totalRepairs,
      spentUsd,
    });
  }

  return { measured, skipped };
}

async function costForUsage(
  modelId: string,
  inputTokens: number,
  outputTokens: number,
): Promise<number> {
  const { getModel, costForTokens } = await import('../src/core/pricing');
  const model = getModel(modelId);
  if (!model) return 0;
  return (
    costForTokens(inputTokens, model.input_per_mtok) +
    costForTokens(outputTokens, model.output_per_mtok)
  );
}

function fmtPct(value: number): string {
  return `${value.toFixed(1)}%`;
}

function levelLabel(level: Level): string {
  return level[0]!.toUpperCase() + level.slice(1);
}

interface GroupResult {
  group: CorpusGroup;
  corpusSize: number;
  fast: LevelStats[];
}

function renderFastTable(result: GroupResult): string[] {
  const lines: string[] = [];
  lines.push(`**${result.group.title}** (${result.corpusSize} prompts)`);
  lines.push('');
  lines.push(`_${result.group.blurb}_`);
  lines.push('');
  lines.push(
    '| Level | Avg. token reduction | Aggregate token reduction | Critical constraints preserved | Changes blocked by the ledger |',
  );
  lines.push('|---|---|---|---|---|');
  for (const row of result.fast) {
    lines.push(
      `| ${levelLabel(row.level)} | ${fmtPct(row.avgReductionPct)} | ${fmtPct(row.aggregateReductionPct)} (${row.tokensBefore.toLocaleString()} → ${row.tokensAfter.toLocaleString()} tokens) | ${fmtPct(row.criticalPreservedPct)} (${row.criticalKept}/${row.criticalTotal}) | ${row.blockedChanges} (${row.promptsWithBlockedChanges} prompt${row.promptsWithBlockedChanges === 1 ? '' : 's'}) |`,
    );
  }
  lines.push('');
  return lines;
}

function renderMarkdown(
  today: string,
  groups: GroupResult[],
  ai: { measured: AiProviderStats[]; skipped: AiSkipped[] },
): string {
  const lines: string[] = [];
  lines.push(
    `_Generated by \`npm run bench\` on ${today}. Tokens counted with the real o200k tokenizer (\`js-tiktoken\`) — never estimated. The ledger is enforced at every level here (the product default only enforces it at Aggressive) so blocked changes are visible at all three._`,
  );
  lines.push('');

  for (const group of groups) {
    lines.push(...renderFastTable(group));
  }

  if (ai.measured.length > 0) {
    lines.push(
      `AI mode, Balanced level, ${AI_SAMPLE_SIZE}-prompt sample from the everyday corpus (a real provider call costs real money, so the sample is small on purpose):`,
    );
    lines.push('');
    lines.push(
      '| Provider | Compress model | Verify model | Critical constraints preserved | API calls | Repairs | Cost for the sample |',
    );
    lines.push('|---|---|---|---|---|---|---|');
    for (const row of ai.measured) {
      lines.push(
        `| ${row.label} | \`${row.compressModel}\` | \`${row.verifyModel}\` | ${fmtPct(row.criticalPreservedPct)} (${row.criticalKeptAfterRepair}/${row.criticalTotal}) | ${row.totalCalls} | ${row.totalRepairs} | $${row.spentUsd.toFixed(4)} |`,
      );
    }
    lines.push('');
  }
  if (ai.skipped.length > 0) {
    const names = [...new Set(ai.skipped.map((s) => s.label))].join(', ');
    lines.push(
      `AI mode not measured for: ${names}. Set the matching API key (\`ANTHROPIC_API_KEY\`, \`OPENAI_API_KEY\`, \`GEMINI_API_KEY\`) and re-run \`npm run bench\` to include it — no percentage is published for a provider that was not actually called.`,
    );
    lines.push('');
  }

  return lines.join('\n').trimEnd();
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * The landing page is static HTML, not a markdown renderer: the same numbers
 * as `renderMarkdown` above, as a real `<table>` reusing the Cost Advisor's
 * existing `.advisor-scroll`/`.advisor-table` styles rather than inventing a
 * parallel set of CSS just for this section.
 */
function renderHtml(
  today: string,
  groups: GroupResult[],
  ai: { measured: AiProviderStats[]; skipped: AiSkipped[] },
): string {
  const lines: string[] = [];
  lines.push(
    `<p class="advisor-sub">Generated by <code>npm run bench</code> on ${today}. Tokens counted with the real o200k tokenizer (js-tiktoken) — never estimated. The ledger is enforced at every level here (the product default only enforces it at Aggressive) so blocked changes are visible at all three.</p>`,
  );

  for (const result of groups) {
    lines.push(`<h3>${escapeHtml(result.group.title)} (${result.corpusSize} prompts)</h3>`);
    lines.push(`<p class="advisor-sub">${escapeHtml(result.group.blurb)}</p>`);
    lines.push('<div class="advisor-scroll"><table class="advisor-table">');
    lines.push(
      '<thead><tr><th scope="col">Level</th><th scope="col">Avg. token reduction</th><th scope="col">Aggregate token reduction</th><th scope="col">Critical constraints preserved</th><th scope="col">Changes blocked by the ledger</th></tr></thead>',
    );
    lines.push('<tbody>');
    for (const row of result.fast) {
      lines.push(
        `<tr><th scope="row">${levelLabel(row.level)}</th><td>${fmtPct(row.avgReductionPct)}</td><td>${fmtPct(row.aggregateReductionPct)} (${row.tokensBefore.toLocaleString()} → ${row.tokensAfter.toLocaleString()})</td><td>${fmtPct(row.criticalPreservedPct)} (${row.criticalKept}/${row.criticalTotal})</td><td>${row.blockedChanges}</td></tr>`,
      );
    }
    lines.push('</tbody></table></div>');
  }

  if (ai.measured.length > 0) {
    lines.push(
      `<p class="advisor-sub">AI mode, Balanced level, ${AI_SAMPLE_SIZE}-prompt sample from the everyday corpus:</p>`,
    );
    lines.push('<div class="advisor-scroll"><table class="advisor-table">');
    lines.push(
      '<thead><tr><th scope="col">Provider</th><th scope="col">Compress model</th><th scope="col">Verify model</th><th scope="col">Critical constraints preserved</th><th scope="col">API calls</th><th scope="col">Repairs</th><th scope="col">Cost for the sample</th></tr></thead>',
    );
    lines.push('<tbody>');
    for (const row of ai.measured) {
      lines.push(
        `<tr><th scope="row">${escapeHtml(row.label)}</th><td>${escapeHtml(row.compressModel)}</td><td>${escapeHtml(row.verifyModel)}</td><td>${fmtPct(row.criticalPreservedPct)} (${row.criticalKeptAfterRepair}/${row.criticalTotal})</td><td>${row.totalCalls}</td><td>${row.totalRepairs}</td><td>$${row.spentUsd.toFixed(4)}</td></tr>`,
      );
    }
    lines.push('</tbody></table></div>');
  }
  if (ai.skipped.length > 0) {
    const names = [...new Set(ai.skipped.map((s) => s.label))].join(', ');
    lines.push(
      `<p class="advisor-sub">AI mode not measured for: ${escapeHtml(names)}. No percentage is published for a provider that was not actually called.</p>`,
    );
  }

  return lines.join('\n');
}

function updateMarkedBlock(filePath: string, marker: string, content: string): void {
  const start = `<!-- BENCHMARK:${marker}:START -->`;
  const end = `<!-- BENCHMARK:${marker}:END -->`;
  const text = readFileSync(filePath, 'utf8');
  const startIdx = text.indexOf(start);
  const endIdx = text.indexOf(end);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`bench: markers "${marker}" not found in ${filePath}`);
  }
  const before = text.slice(0, startIdx + start.length);
  const after = text.slice(endIdx);
  writeFileSync(filePath, `${before}\n${content}\n${after}`);
}

async function main(): Promise<void> {
  const today = new Date().toISOString().slice(0, 10);

  const groupResults: GroupResult[] = [];
  let aiCorpus: CorpusEntry[] = [];
  for (const group of CORPUS_GROUPS) {
    const corpus = loadCorpus(group.dirs);
    console.log(`Running bench on "${group.title}" (${corpus.length} prompts)…`);
    const fast = await benchFastMode(corpus);
    groupResults.push({ group, corpusSize: corpus.length, fast });
    if (group.id === AI_SAMPLE_GROUP) aiCorpus = corpus;
  }

  const ai = await benchAiMode(aiCorpus);
  const markdown = renderMarkdown(today, groupResults, ai);
  const html = renderHtml(today, groupResults, ai);

  const resultsDir = join(ROOT, 'bench', 'results');
  mkdirSync(resultsDir, { recursive: true });
  writeFileSync(
    join(resultsDir, 'summary.json'),
    JSON.stringify(
      {
        generatedAt: today,
        groups: groupResults.map((g) => ({
          id: g.group.id,
          title: g.group.title,
          corpusSize: g.corpusSize,
          fast: g.fast,
        })),
        ai,
      },
      null,
      2,
    ) + '\n',
  );
  writeFileSync(join(resultsDir, 'summary.md'), markdown + '\n');

  updateMarkedBlock(join(ROOT, 'README.md'), 'README', markdown);
  updateMarkedBlock(join(ROOT, 'index.html'), 'LANDING', html);

  for (const { group, fast } of groupResults) {
    for (const row of fast) {
      console.log(
        `[${group.id}] ${levelLabel(row.level)}: ${fmtPct(row.avgReductionPct)} avg reduction, ${fmtPct(row.criticalPreservedPct)} critical constraints preserved, ${row.blockedChanges} blocked changes`,
      );
    }
  }
  if (ai.measured.length) {
    for (const row of ai.measured) {
      console.log(
        `AI ${row.label}: ${fmtPct(row.criticalPreservedPct)} critical constraints preserved`,
      );
    }
  }
  if (ai.skipped.length) {
    console.log(`AI mode skipped for: ${[...new Set(ai.skipped.map((s) => s.label))].join(', ')}`);
  }

  console.log(
    '\nWritten: bench/results/summary.json, bench/results/summary.md, README.md, index.html',
  );
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
